#!/usr/bin/env python3
"""BLML QA helper: seeds test accounts on a LOCAL server and plays the "other
person" in a chat while an app is being tested.

    qa/blml_qa.py seed                      # create the test accounts (idempotent)
    qa/blml_qa.py whoami  qa_peer
    qa/blml_qa.py send    qa_peer qa_ios "hello"          # p2p message to a test account
    qa/blml_qa.py send    qa_peer grpXXXX "hello group"   # or to a topic id
    qa/blml_qa.py reply   qa_peer qa_ios 3 "replying to seq 3"
    qa/blml_qa.py edit    qa_peer qa_ios 4 "edited text"
    qa/blml_qa.py delete  qa_peer qa_ios 4                # delete for everyone
    qa/blml_qa.py typing  qa_peer qa_ios
    qa/blml_qa.py read    qa_peer qa_ios                  # mark everything read
    qa/blml_qa.py history qa_peer qa_ios [N]              # last N messages, both sides
    qa/blml_qa.py listen  qa_peer [SECONDS]               # print what arrives
    qa/blml_qa.py group   qa_peer "QA group" qa_ios qa_android qa_web
    qa/blml_qa.py find    qa_peer "+61491570101"          # directory search
    qa/blml_qa.py topics  qa_peer                         # the account's chat list
    qa/blml_qa.py sendfile qa_peer qa_ios photo.jpg ["caption"]  # image or video (mp4/mov) as an attachment

  1:1 chat requests (qa/runs/2026-10-02/contract-friend-requests.md). A NEW chat is a
  request: `send` to someone you have no chat with yet answers 403 not-accepted.
    qa/blml_qa.py request qa_peer3 qa_ios                 # qa_peer3 asks qa_ios to chat (plain sub)
    qa/blml_qa.py accept  qa_peer3 qa_ios                 # qa_peer3 accepts a request FROM qa_ios
    qa/blml_qa.py decline qa_peer3 qa_ios                 # the apps' Ignore: del topic hard
    qa/blml_qa.py block   qa_peer3 qa_ios                 # want -JP
    qa/blml_qa.py unblock qa_peer3 qa_ios                 # want +JP (a blocked request returns to pending)
    qa/blml_qa.py state   qa_peer3 qa_ios                 # own/peer acs + pending/accepted/blocked
    qa/blml_qa.py newuser qa_req1 "QA Request One" [+61491570111]  # extra throwaway account (chat requests)
    qa/blml_qa.py accept  qa_req1 qa_ios                  # accept a pending 1:1 chat request

Logins and generated passwords live in qa/test-accounts.env (gitignored). This
tool refuses to talk to anything but a server on this machine: the accounts it
creates are throwaway, and production must never collect them.
"""
import base64
import json
import os
import secrets
import sys
import time
from pathlib import Path

from websocket import create_connection

HERE = Path(__file__).resolve().parent
ACCOUNTS_FILE = HERE / "test-accounts.env"
HOST = os.environ.get("QA_HOST", "localhost:6060")
API_KEY = "AQAAAAABAAC-d-KsShjNeHzNi7myV36_"  # same key the apps ship with

if HOST.split(":")[0] not in ("localhost", "127.0.0.1", "[::1]"):
    sys.exit(f"refusing to run against {HOST}: QA accounts belong on a local server only")

# Phone numbers come from ACMA's reserved range for fiction (0491 570 xxx), so
# they can never belong to a real person.
ACCOUNTS = [
    ("qa_ios", "QA iPhone", "+61491570101"),
    ("qa_android", "QA Android", "+61491570102"),
    ("qa_web", "QA Web", "+61491570103"),
    ("qa_peer", "QA Peer", "+61491570104"),
    ("qa_peer2", "QA Peer Two", "+61491570105"),
]


def invite_code():
    for line in (HERE.parent / "deploy" / "secrets.env").read_text().splitlines():
        if line.startswith("REGISTRATION_CODE="):
            return line.split("=", 1)[1].strip().strip('"')
    sys.exit("REGISTRATION_CODE not found in deploy/secrets.env")


def load_accounts():
    accts = {}
    if ACCOUNTS_FILE.exists():
        for line in ACCOUNTS_FILE.read_text().splitlines():
            if line.startswith("#") or "=" not in line:
                continue
            key, val = line.split("=", 1)
            login, field = key.rsplit("__", 1)
            accts.setdefault(login.lower(), {})[field.lower()] = val
    return accts


def save_accounts(accts):
    lines = ["# BLML QA test accounts for the LOCAL server only. Generated by qa/blml_qa.py seed.",
             "# Never reuse these anywhere else; never commit this file."]
    for login, a in accts.items():
        for field in ("password", "uid", "phone", "name"):
            if field in a:
                lines.append(f"{login.upper()}__{field.upper()}={a[field]}")
    ACCOUNTS_FILE.write_text("\n".join(lines) + "\n")
    ACCOUNTS_FILE.chmod(0o600)


class Session:
    def __init__(self):
        self.ws = create_connection(f"ws://{HOST}/v0/channels?apikey={API_KEY}", timeout=8)
        self.n = 0
        self.backlog = []
        self.call({"hi": {"ver": "0.23", "ua": "blml-qa/1.0", "lang": "en"}})

    def call(self, msg, tries=40):
        """Send one message and return its ctrl reply. Other frames that arrive
        meanwhile are kept in self.backlog."""
        self.n += 1
        mid = str(self.n)
        (next(iter(msg.values())))["id"] = mid
        self.ws.send(json.dumps(msg))
        for _ in range(tries):
            frame = json.loads(self.ws.recv())
            if "ctrl" in frame and frame["ctrl"].get("id") == mid:
                return frame["ctrl"]
            self.backlog.append(frame)
        raise RuntimeError(f"no reply to {msg}")

    def login(self, login, password):
        secret = base64.b64encode(f"{login}:{password}".encode()).decode()
        c = self.call({"login": {"scheme": "basic", "secret": secret}})
        if c["code"] >= 300:
            raise RuntimeError(f"login {login}: {c['code']} {c.get('text')}")
        self.token = c["params"].get("token")
        return c["params"]["user"]


def session_for(login):
    accts = load_accounts()
    if login not in accts:
        sys.exit(f"unknown test account {login}; run `seed` first")
    s = Session()
    s.uid = s.login(login, accts[login]["password"])
    return s


def topic_for(target):
    """A test-account login becomes its p2p topic (usr<uid>); anything else is a topic id."""
    accts = load_accounts()
    if target in accts:
        return "usr" + accts[target]["uid"].removeprefix("usr")
    return target


def join(s, topic, history=0):
    get = {"what": "desc sub data", "data": {"limit": history}} if history else {"what": "desc sub"}
    c = s.call({"sub": {"topic": topic, "get": get}}, tries=200)
    if c["code"] >= 300:
        raise RuntimeError(f"sub {topic}: {c['code']} {c.get('text')}")
    if history:
        drain(s)  # data frames follow the ctrl reply
    return c.get("topic", topic)


def drain(s, seconds=1.5):
    """Collect frames that keep arriving after a reply, until the line goes quiet."""
    s.ws.settimeout(seconds)
    try:
        while True:
            s.backlog.append(json.loads(s.ws.recv()))
    except Exception:
        pass
    s.ws.settimeout(8)


def cmd_seed():
    accts = load_accounts()
    code = invite_code()
    for login, name, phone in ACCOUNTS:
        a = accts.setdefault(login, {})
        a.setdefault("password", secrets.token_urlsafe(12))
        a["name"], a["phone"] = name, phone
        s = Session()
        try:
            a["uid"] = s.login(login, a["password"])
            print(f"exists   {login}")
        except RuntimeError:
            secret = base64.b64encode(f"{login}:{a['password']}".encode()).decode()
            c = s.call({"acc": {"user": "new", "scheme": "basic", "secret": secret, "login": True,
                                "tags": ["code:" + code],
                                "desc": {"public": {"fn": name}}}})
            if c["code"] >= 300:
                sys.exit(f"create {login}: {c['code']} {c.get('text')}")
            a["uid"] = c["params"]["user"]
            print(f"created  {login}")
        c = s.call({"sub": {"topic": "me"}})
        c = s.call({"set": {"topic": "me", "cred": {"meth": "tel", "val": phone}}})
        print(f"         phone {phone}: {c['code']} {c.get('text')}")
        s.ws.close()
    save_accounts(accts)
    print(f"saved logins to {ACCOUNTS_FILE.relative_to(HERE.parent)}")


def cmd_newuser(login, name, phone=None):
    """A fresh account with no chats yet, for testing 1:1 chat requests."""
    accts = load_accounts()
    a = accts.setdefault(login, {})
    a.setdefault("password", secrets.token_urlsafe(12))
    a["name"] = name
    if phone:
        a["phone"] = phone
    s = Session()
    try:
        a["uid"] = s.login(login, a["password"])
        print(f"exists   {login}")
    except RuntimeError:
        secret = base64.b64encode(f"{login}:{a['password']}".encode()).decode()
        c = s.call({"acc": {"user": "new", "scheme": "basic", "secret": secret, "login": True,
                            "tags": ["code:" + invite_code()], "desc": {"public": {"fn": name}}}})
        if c["code"] >= 300:
            sys.exit(f"create {login}: {c['code']} {c.get('text')}")
        a["uid"] = c["params"]["user"]
        print(f"created  {login} {a['uid']}")
    if phone:
        s.call({"sub": {"topic": "me"}})
        c = s.call({"set": {"topic": "me", "cred": {"meth": "tel", "val": phone}}})
        print(f"         phone {phone}: {c['code']} {c.get('text')}")
    s.ws.close()
    save_accounts(accts)


def cmd_accept(login, target):
    """Recipient accepts a 1:1 chat request (contract 3.3): own want with W."""
    s = session_for(login)
    topic = topic_for(target)
    c = s.call({"sub": {"topic": topic, "set": {"sub": {"mode": "JRWPAD"}}, "get": {"what": "desc sub"}}})
    print(json.dumps({"code": c["code"], "text": c.get("text"), "acs": (c.get("params") or {}).get("acs")}))


def _acs_state(own, peer):
    """Classify a p2p chat as in contract-friend-requests.md section 2."""
    w, g = own.get("want") or "", own.get("given") or ""
    if "J" not in w:
        return "blocked by me"
    if peer and "J" not in (peer.get("want") or ""):
        return "blocked by peer"
    if "R" not in w and "W" not in w and "J" in g:
        return "pending incoming (request to accept)"
    if "W" in w and "W" not in g:
        return "pending outgoing (request sent / declined)"
    if "W" in w and "W" in g:
        return "accepted"
    return "other"


def cmd_request(login, target):
    """Requester side of a 1:1 chat request (contract 3.1): a plain {sub}. Prints the acs."""
    s = session_for(login)
    c = s.call({"sub": {"topic": topic_for(target), "get": {"what": "desc sub"}}}, tries=200)
    acs = (c.get("params") or {}).get("acs") or {}
    print(json.dumps({"code": c["code"], "text": c.get("text"), "acs": acs,
                      "state": _acs_state(acs, None) if acs else None}))


def cmd_decline(login, target):
    """Recipient declines a request (contract 3.4): {del topic hard}, the apps' Ignore."""
    s = session_for(login)
    c = s.call({"del": {"topic": topic_for(target), "what": "topic", "hard": True}})
    print(json.dumps({"code": c["code"], "text": c.get("text")}))


def _set_want(login, target, delta):
    s = session_for(login)
    topic = topic_for(target)
    s.call({"sub": {"topic": topic, "get": {"what": "desc"}}}, tries=200)
    drain(s, 1.0)  # {meta desc} follows the ctrl
    want = ""
    for f in s.backlog:
        acs = ((f.get("meta") or {}).get("desc") or {}).get("acs")
        if acs:
            want = acs.get("want") or ""
    out, sign = set(want.replace("N", "")), None
    for ch in delta:
        if ch in "+-":
            sign = ch
        elif sign == "+":
            out.add(ch)
        else:
            out.discard(ch)
    mode = "".join(ch for ch in "JRWPASDO" if ch in out) or "N"
    c = s.call({"set": {"topic": topic, "sub": {"mode": mode}}})
    print(json.dumps({"code": c["code"], "text": c.get("text"), "want": mode}))


def cmd_state(login, target):
    """Own and peer access modes of a p2p chat, classified per the contract."""
    s = session_for(login)
    s.call({"sub": {"topic": topic_for(target), "get": {"what": "desc sub"}}}, tries=200)
    drain(s, 1.0)
    own, peer = {}, {}
    for f in s.backlog:
        m = f.get("meta") or {}
        if (m.get("desc") or {}).get("acs"):
            own = m["desc"]["acs"]
        for sub in m.get("sub") or []:
            if sub.get("user") and sub.get("user") != s.uid:
                peer = sub.get("acs") or {}
    print(json.dumps({"own": own, "peer": peer, "state": _acs_state(own, peer)}))


def cmd_send(login, target, text, head=None):
    s = session_for(login)
    topic = join(s, topic_for(target))
    msg = {"topic": topic, "content": text, "noecho": False}
    if head:
        msg["head"] = head
    c = s.call({"pub": msg})
    print(json.dumps({"code": c["code"], "topic": topic, "seq": (c.get("params") or {}).get("seq")}))


def _upload(s, path):
    """POST the file to the server's upload endpoint; returns the relative download URL."""
    import mimetypes
    import urllib.request
    data = Path(path).read_bytes()
    mime = mimetypes.guess_type(path)[0] or "application/octet-stream"
    boundary = "blmlqa" + secrets.token_hex(8)
    body = (f"--{boundary}\r\nContent-Disposition: form-data; name=\"file\"; filename=\"{Path(path).name}\"\r\n"
            f"Content-Type: {mime}\r\n\r\n").encode() + data + f"\r\n--{boundary}--\r\n".encode()
    req = urllib.request.Request(f"http://{HOST}/v0/file/u/", data=body, method="POST", headers={
        "Content-Type": f"multipart/form-data; boundary={boundary}",
        "X-Tinode-APIKey": API_KEY,
        "X-Tinode-Auth": f"Token {s.token}",
    })
    with urllib.request.urlopen(req) as resp:
        ctrl = json.loads(resp.read())["ctrl"]
    if ctrl["code"] >= 300:
        raise RuntimeError(f"upload: {ctrl}")
    return ctrl["params"]["url"], mime, len(data)


def cmd_sendfile(login, target, path, caption=""):
    """Sends an image or a video as an out-of-band attachment, the way the apps do."""
    import subprocess
    import tempfile
    s = session_for(login)
    topic = join(s, topic_for(target))
    url, mime, size = _upload(s, path)
    name = Path(path).name
    if mime.startswith("image/"):
        from PIL import Image
        w, h = Image.open(path).size
        ent = {"tp": "IM", "data": {"mime": mime, "ref": url, "width": w, "height": h, "name": name, "size": size}}
    elif mime.startswith("video/"):
        probe = json.loads(subprocess.run(
            ["ffprobe", "-v", "error", "-select_streams", "v:0", "-show_entries", "stream=width,height:format=duration",
             "-of", "json", path], capture_output=True, check=True).stdout)
        w, h = probe["streams"][0]["width"], probe["streams"][0]["height"]
        duration = int(float(probe["format"]["duration"]) * 1000)
        with tempfile.TemporaryDirectory() as tmp:
            poster = Path(tmp) / "poster.png"
            subprocess.run(["ffmpeg", "-v", "error", "-y", "-i", path, "-frames:v", "1", "-vf", "scale=320:-2", str(poster)], check=True)
            preview = base64.b64encode(poster.read_bytes()).decode()
        ent = {"tp": "VD", "data": {"mime": mime, "ref": url, "width": w, "height": h, "duration": duration,
                                     "name": name, "size": size, "premime": "image/png", "preview": preview}}
    else:
        ent = {"tp": "EX", "data": {"mime": mime, "ref": url, "name": name, "size": size}}
    txt = " " + (("\n" + caption) if caption else "")
    content = {"txt": txt, "fmt": [{"at": 0, "len": 1, "key": 0}], "ent": [ent]}
    if caption:
        content["fmt"].append({"at": 1, "len": 1, "tp": "BR"})
    c = s.call({"pub": {"topic": topic, "content": content, "head": {"mime": "text/x-drafty"},
                        "extra": {"attachments": [url]}, "noecho": False}})
    print(json.dumps({"code": c["code"], "topic": topic, "seq": (c.get("params") or {}).get("seq"), "ref": url}))


def cmd_delete(login, target, seq):
    s = session_for(login)
    topic = join(s, topic_for(target))
    c = s.call({"del": {"topic": topic, "what": "msg", "delseq": [{"low": int(seq)}], "hard": True}})
    print(json.dumps({"code": c["code"], "text": c.get("text")}))


def cmd_note(login, target, what):
    s = session_for(login)
    topic = join(s, topic_for(target), history=1)
    note = {"topic": topic, "what": what}
    if what == "read":
        seqs = [f["data"]["seq"] for f in s.backlog if "data" in f]
        if not seqs:
            print("nothing to mark read")
            return
        note["seq"] = max(seqs)
    s.ws.send(json.dumps({"note": note}))
    time.sleep(1)
    print(f"sent {what} on {topic}")


def describe(f, me):
    d = f["data"]
    who = "me" if d.get("from") == me else d.get("from")
    head = {k: v for k, v in (d.get("head") or {}).items() if k in ("reply", "replace", "forwarded", "mime")}
    content = d.get("content")
    if isinstance(content, dict):  # Drafty: show text plus attachment kinds
        kinds = [e.get("tp") for e in content.get("ent", [])]
        content = (content.get("txt") or "") + (f"  [{', '.join(kinds)}]" if kinds else "")
    return f"{d['topic']} seq={d['seq']} from={who} {head or ''} {content!r}"


def cmd_history(login, target, n="20"):
    s = session_for(login)
    join(s, topic_for(target), history=int(n))
    for f in s.backlog:
        if "data" in f:
            print(describe(f, s.uid))


def cmd_listen(login, seconds="30"):
    s = session_for(login)
    s.call({"sub": {"topic": "me", "get": {"what": "sub"}}})
    drain(s)
    topics = [t["topic"] for f in s.backlog if "meta" in f for t in f["meta"].get("sub", [])]
    for t in topics:
        join(s, t)
    s.backlog.clear()
    print(f"listening as {login} on {len(topics)} topics for {seconds}s")
    s.ws.settimeout(1)
    end = time.time() + float(seconds)
    while time.time() < end:
        try:
            f = json.loads(s.ws.recv())
        except Exception:
            continue
        if "data" in f:
            print(describe(f, s.uid), flush=True)
        elif "info" in f:
            i = f["info"]
            print(f"info {i.get('topic')} {i.get('what')} seq={i.get('seq')} from={i.get('from')}", flush=True)
        elif "pres" in f:
            p = f["pres"]
            print(f"pres {p.get('topic')} {p.get('what')} src={p.get('src')}", flush=True)


def cmd_group(login, name, *members):
    s = session_for(login)
    c = s.call({"sub": {"topic": "new", "set": {"desc": {"public": {"fn": name}}}}})
    topic = c["topic"]
    for m in members:
        uid = topic_for(m).removeprefix("usr")
        c = s.call({"set": {"topic": topic, "sub": {"user": "usr" + uid}}})
        print(f"invite {m}: {c['code']}")
    print(json.dumps({"topic": topic}))


def cmd_find(login, query):
    s = session_for(login)
    s.call({"sub": {"topic": "fnd"}})
    s.call({"set": {"topic": "fnd", "desc": {"public": query}}})
    s.ws.send(json.dumps({"get": {"id": "f", "topic": "fnd", "what": "sub"}}))
    s.ws.settimeout(3)
    try:
        while True:
            f = json.loads(s.ws.recv())
            if "meta" in f:
                for sub in f["meta"].get("sub", []):
                    print(sub.get("user") or sub.get("topic"), (sub.get("public") or {}).get("fn"))
                break
            if "ctrl" in f and f["ctrl"].get("id") == "f":
                print(f"no results ({f['ctrl']['code']})")
                break
    except Exception:
        print("no results")


def cmd_topics(login):
    s = session_for(login)
    s.call({"sub": {"topic": "me", "get": {"what": "sub"}}})
    drain(s)
    for f in s.backlog:
        for t in (f.get("meta") or {}).get("sub", []):
            print(t["topic"], (t.get("public") or {}).get("fn"), "mode=" + (t.get("acs") or {}).get("mode", "?"),
                  "seq=%s read=%s" % (t.get("seq"), t.get("read")))


def cmd_whoami(login):
    s = session_for(login)
    print(s.uid)


COMMANDS = {
    "seed": lambda: cmd_seed(),
    "whoami": cmd_whoami,
    "send": cmd_send,
    "reply": lambda login, target, seq, text: cmd_send(login, target, text, {"reply": str(seq)}),
    "edit": lambda login, target, seq, text: cmd_send(login, target, text, {"replace": ":" + str(seq)}),
    "delete": cmd_delete,
    "typing": lambda login, target: cmd_note(login, target, "kp"),
    "read": lambda login, target: cmd_note(login, target, "read"),
    "history": cmd_history,
    "listen": cmd_listen,
    "group": cmd_group,
    "find": cmd_find,
    "topics": cmd_topics,
    "sendfile": cmd_sendfile,
    "newuser": cmd_newuser,
    "accept": cmd_accept,
    "request": cmd_request,
    "decline": cmd_decline,
    "block": lambda login, target: _set_want(login, target, "-JP"),
    "unblock": lambda login, target: _set_want(login, target, "+JP"),
    "state": cmd_state,
}

if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] not in COMMANDS:
        sys.exit(__doc__)
    COMMANDS[sys.argv[1]](*sys.argv[2:])
